services:
  - type: web
    name: coinixfaucet-backend
    runtime: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: FIREBASE_PROJECT_ID
        value: coinixfaucet
      - key: RECAPTCHA_SITE_KEY
        value: 6LctET4tAAAAAAGcqEdyQbF_gcTH57Dnxztlv2hN
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: OFFERWALL_API_KEY
        sync: false
      - key: OFFERWALL_SECRET_KEY
        sync: false
      - key: ADMIN_SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://coinixfaucet.mine.bz
